name = "Construct"
uuid = "a93a0f36-edeb-11e9-0b4d-9362483990c2"
authors = ["Anand Jain"]
version = "0.1.0"

[compat]
julia = "1.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
